# Runs the Dapr Windows Powershell Install Script

name: Run Dapr Windows Install Script

on:
  push:
    branches: [ master ]
    paths:
      - 'install/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'install/**'
  release:
    types:
      - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Dapr
      - name: Install DAPR CLI
        run: powershell "install/install.ps1"
